#!/usr/bin/env php
<?php

/**
 * @param $url
 * @param $data
 * @return \stdClass
 */
function httpPost($url, $data)
{
    $curl = curl_init($url);
    curl_setopt($curl, CURLOPT_POST, true);
    curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query($data));
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    $response = curl_exec($curl);
    curl_close($curl);

    return json_decode($response);
}

list(, $size, $token, $server,) = $argv;
$users = array_splice($argv, 4);

if (disk_free_space('/') - ($size << 30) <= 0 && isset($size, $token) && !empty($users)) {
    $remainder = round(disk_free_space('/') / (1 << 30), 3, PHP_ROUND_HALF_DOWN);
    foreach ($users as $user) {
        httpPost('https://api.telegram.org/bot'.$token.'/sendMessage', [
            'chat_id' => $user,
            'text' => $server.' Алёрт! Ахтунг! Память кончается! Осталось '.$remainder.'Gb',
        ]);
    }
} else {
    echo 'OK';
}
