#!/usr/bin/env php
<?php

function httpPost($url, $data)
{
    $curl = curl_init($url);
    curl_setopt($curl, CURLOPT_POST, true);
    curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query($data));
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    $response = curl_exec($curl);
    curl_close($curl);

    return $response;
}

$users = [];

foreach ($argv as $index => $arg) {
    switch ($index) {
        case 0:
            break;
        case 1:
            $size = $arg;
            break;
        case 2:
            $token = $arg;
            break;
        default:
            $users[] = $arg;
    }
}

if (disk_free_space('/') - ($size << 30) <= 0 && isset($size, $token, $users) && !empty($users)) {
    foreach ($users as $user) {
        httpPost('https://api.telegram.org/bot'.$token.'/sendMessage', [
            'chat_id' => $user,
            'text' => 'Алёрт! Ахтунг! Память кончается!',
        ]);
    }
} else {
    echo 'OK';
}

